import { BeatCard } from "@/components/BeatCard";
import { usePageMeta } from "@/hooks/usePageMeta";
import { loadCategories, loadPublishedBeats } from "@/lib/marketplace";
import type { Beat, Category } from "@/lib/models";
import { Grid2X2, List, Search, SlidersHorizontal } from "lucide-react";
import { useEffect, useState } from "react";

export default function Explore() {
  usePageMeta("Browse beats", "Search BeatBox by genre, mood, BPM, and producer to find an original beat for your next track.");
  const [beats, setBeats] = useState<Beat[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState(""); const [genre, setGenre] = useState("all"); const [mood, setMood] = useState("all"); const [minBpm, setMinBpm] = useState(""); const [maxBpm, setMaxBpm] = useState(""); const [mode, setMode] = useState<"grid" | "list">("grid");

  const refresh = () => { setLoading(true); loadPublishedBeats({ search, genre, mood, minBpm: Number(minBpm) || undefined, maxBpm: Number(maxBpm) || undefined }).then(setBeats).catch(() => setBeats([])).finally(() => setLoading(false)); };
  useEffect(() => { loadCategories().then(setCategories).catch(() => setCategories([])); refresh(); }, []);

  return <section className="explore-page"><div className="container"><div className="page-intro"><p className="eyebrow"><span /> Discover the catalog</p><h1>Find your next sound.</h1><p>Search original beats by mood, genre, and tempo. Guests can stream every published release; private master downloads remain protected until sign-in and entitlement are verified.</p></div><form className="filters" onSubmit={event => { event.preventDefault(); refresh(); }}><div className="search-field"><Search size={19} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search title, producer, or genre" aria-label="Search beats" /></div><select value={genre} onChange={event => setGenre(event.target.value)}><option value="all">All genres</option>{categories.map(category => <option key={category.id} value={category.name}>{category.name}</option>)}</select><select value={mood} onChange={event => setMood(event.target.value)}><option value="all">Any mood</option><option value="Chill">Chill</option><option value="Dark">Dark</option><option value="Energetic">Energetic</option><option value="Soulful">Soulful</option></select><input type="number" value={minBpm} onChange={event => setMinBpm(event.target.value)} placeholder="Min BPM" min="40" max="260" /><input type="number" value={maxBpm} onChange={event => setMaxBpm(event.target.value)} placeholder="Max BPM" min="40" max="260" /><button className="button button--small" type="submit"><SlidersHorizontal size={16} /> Apply</button></form><div className="catalog-toolbar"><p>{loading ? "Loading catalog…" : `${beats.length} published ${beats.length === 1 ? "beat" : "beats"}`}</p><div className="view-toggle"><button className={mode === "grid" ? "is-active" : ""} type="button" onClick={() => setMode("grid")} aria-label="Grid view"><Grid2X2 size={18} /></button><button className={mode === "list" ? "is-active" : ""} type="button" onClick={() => setMode("list")} aria-label="List view"><List size={18} /></button></div></div>{loading ? <div className="skeleton-grid">{Array.from({ length: 6 }).map((_, index) => <div className="skeleton-card" key={index} />)}</div> : beats.length ? <div className={mode === "grid" ? "beat-grid" : "beat-list"}>{beats.map(beat => <BeatCard key={beat.id} beat={beat} mode={mode} />)}</div> : <div className="empty-featured empty-featured--light"><Search size={32} /><h2>No published beats match those filters.</h2><p>Try a broader search or return later as producers grow the catalog.</p></div>}</div></section>;
}
