import { Loader2, Play, Volume2 } from "lucide-react";
import React, { useEffect, useState } from "react";
import { Link } from "wouter";
import type { SocialPost } from "@/lib/models";
import { supabase } from "@/lib/supabase";
import { useSupabaseAuth } from "@/contexts/SupabaseAuthContext";
import { SocialActions } from "@/components/SocialActions";

export default function Reels() {
  const { user } = useSupabaseAuth();
  const [posts, setPosts] = useState<SocialPost[]>([]);
  const [urls, setUrls] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; const load = async () => { const reels = await supabase.from("social_reels").select("post_id,caption,creator_id,social_posts(id,author_id,body,media_path,media_type,like_count,comment_count,share_count,created_at,profiles(display_name,avatar_url))").eq("status", "published").order("created_at", { ascending: false }).limit(30); if (!active) return; const next = (reels.data || []).map(row => { const post = Array.isArray(row.social_posts) ? row.social_posts[0] : row.social_posts; const source = post as (SocialPost & { profiles?: SocialPost["profiles"] | SocialPost["profiles"][] }) | null; return source ? { ...source, content_id: source.content_id || null, link_url: source.link_url || null, status: source.status || "published", profiles: Array.isArray(source.profiles) ? source.profiles[0] || null : source.profiles || null } : null; }).filter(Boolean) as SocialPost[]; setPosts(next); const nextUrls: Record<string, string> = {}; next.forEach(post => { if (post.media_path) nextUrls[post.id] = supabase.storage.from("social-media").getPublicUrl(post.media_path).data.publicUrl; }); setUrls(nextUrls); setLoading(false); }; void load(); return () => { active = false; }; }, []);
  return <section className="reels-page"><div className="container"><div className="dashboard-title"><div><p className="eyebrow"><span /> BeatBox Reels</p><h1>Short drops from Liberia’s creators.</h1><p className="muted-copy">Public short videos only. Paid marketplace masters remain protected behind their verified access workflows.</p></div><Link className="button button--small" href="/feed">Back to Feed</Link></div>{loading ? <div className="status-page"><Loader2 className="spin" /><p>Loading Reels…</p></div> : posts.length ? <div className="reels-scroller">{posts.map(post => <article className="reel-card" key={post.id}>{urls[post.id] ? <video className="reel-card__video" controls playsInline preload="metadata" src={urls[post.id]} aria-label={`Reel by ${post.profiles?.display_name || "BeatBox creator"}`} /> : <div className="reel-card__empty"><Play size={28} /><span>Public video unavailable</span></div>}<div className="reel-card__overlay"><div><b>{post.profiles?.display_name || "BeatBox creator"}</b><p>{post.body || "New BeatBox Reel"}</p></div><Volume2 size={18} aria-hidden="true" /></div><SocialActions postId={post.id} userId={user?.id} liked={false} bookmarked={false} likeCount={post.like_count} commentCount={post.comment_count} shareCount={post.share_count} onLike={() => undefined} onSave={() => undefined} onComment={() => undefined} onRepost={() => undefined} onReport={() => undefined} /></article>)}</div> : <div className="empty-featured empty-featured--light"><Play size={34} /><h2>No public Reels yet.</h2><p>Short creator videos will appear here when published.</p></div>}</div></section>;
}
